---
extends:
  - yialo/preset-webpack
globals:
  process: readonly
ignorePatterns:
  - '*.html'
  - /dist/
  - /extra/
overrides:
  - extends:
      - yialo/mixin-jest
    files:
      - ./**/*.{spec,test}.js?(x)
  - extends:
      - yialo/preset-node
    files:
      - ./config/**/*.js
      - ./postcss/**/*.js
  - extends:
      - yialo/mixin-typescript
    files:
      - ./src/**/*.ts?(x)
rules:
  import/no-unassigned-import:
    - error
    - allow:
      - '**/*.{?(s)css,jp?(e)g,png,svg}'
settings:
  import/resolver:
    webpack:
      config: ./config/webpack.config.js
