---
extends:
  - yialo/web
globals:
  process: readonly
ignorePatterns:
  - '*.html'
  - /dist/
  - /extra/
overrides:
  - extends:
      - yialo/web-jest
    files:
      - ./**/*.{spec,test}.js?(x)
  - extends:
      - yialo/web-build
    files:
      - ./config/**/*.js
      - ./postcss/**/*.js
  - extends:
      - yialo/web-typescript
    files:
      - ./src/**/*.ts?(x)
settings:
  import/resolver:
    webpack:
      config: ./config/webpack.config.js
