---
extends:
  - stylelint-config-yialo/base
  - stylelint-config-yialo/scss
ignoreFiles:
  - '**/*.html'
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.md'
  - '**/*.ts'
  - '**/*.tsx'
  - './dist/**'
  - './docs/**'
  - './node_modules/**'
