export const ActionTypeEnum = {
  LIST_SEARCH: 'LIST_SEARCH',
  LIST_FILTER_TOGGLE: 'LIST_FILTER_TOGGLE',
  FETCH_COMPLETE: 'FETCH_COMPLETE',
  FETCH_ERROR: 'FETCH_ERROR',
  THEME_TOGGLE: 'THEME_TOGGLE',
};
